In [ ]:
import numpy as np

Zadanie 1

In [ ]:
a = np.array([1,3,5,2,7])
a

array([1, 3, 5, 2, 7])

In [ ]:
b = np.array([1,3,5.0,2,7])
b

array([1., 3., 5., 2., 7.])

In [ ]:
b = np.array([3.14, 4, 2, 3],dtype=int)
b

array([3, 4, 2, 3])

In [ ]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
d=np.array([[-3.0,2.3],[0.1,5.0],[8.0,11.0]])
d

array([[-3. ,  2.3],
       [ 0.1,  5. ],
       [ 8. , 11. ]])

In [ ]:
e=np.array([[[2,4],[1,2],[8,9]],[[7,6],[-3,4],[0,8]]])
e

array([[[ 2,  4],
        [ 1,  2],
        [ 8,  9]],

       [[ 7,  6],
        [-3,  4],
        [ 0,  8]]])

Zadanie 2

In [ ]:
a.ndim,b.ndim,c.ndim,d.ndim,e.ndim

(1, 1, 3, 2, 3)

In [ ]:
a.shape,b.shape,c.shape,d.shape,e.shape

((5,), (4,), (2, 2, 3), (3, 2), (2, 3, 2))

In [ ]:
a.size, b.size,c.size,d.size,e.size

(5, 4, 12, 6, 12)

In [ ]:
a.dtype,b.dtype,c.dtype,d.dtype,e.dtype

(dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'))

In [ ]:
a.itemsize,b.itemsize,c.itemsize,d.itemsize,e.itemsize

(8, 8, 8, 8, 8)

In [ ]:
a.nbytes,b.nbytes,c.nbytes,d.nbytes,e.nbytes

(40, 32, 96, 48, 96)

Zadanie 3


In [ ]:
X1 = np.random.random((4,3))

X2 = np.zeros((2,1))

X3 = np.full((6,2,1),2)

X4 = np.random.randint(0,7,(5,8))

X5 = np.eye(5)

In [ ]:
X1

array([[0.37851586, 0.88499568, 0.47359443],
       [0.72929307, 0.06215834, 0.6278605 ],
       [0.84064081, 0.62559174, 0.83890048],
       [0.31917853, 0.96891742, 0.39942492]])

In [ ]:
X2

array([[0.],
       [0.]])

In [ ]:
X3

array([[[2],
        [2]],

       [[2],
        [2]],

       [[2],
        [2]],

       [[2],
        [2]],

       [[2],
        [2]],

       [[2],
        [2]]])

In [ ]:
X4

array([[2, 1, 2, 4, 6, 2, 4, 2],
       [2, 3, 4, 4, 5, 1, 0, 1],
       [2, 2, 2, 1, 0, 1, 5, 0],
       [0, 5, 2, 6, 6, 5, 1, 6],
       [4, 1, 4, 3, 0, 6, 3, 2]])

In [ ]:
X5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

ZADANIE TENSORY

In [ ]:
A = np.array([[[1],[2]],[[1],[2]],[[1],[2]]])
A.shape

(3, 2, 1)

In [ ]:
A = np.array([[[1,2]],[[1,2]],[[1,2]]])
A.shape

(3, 1, 2)

In [ ]:
A = np.array([[[1,2,3],[1,2,3]]])
A.shape

(1, 2, 3)

In [ ]:
A = np.array([[[1,2,3]],[[1,2,3]]])
A.shape

(2, 1, 3)

In [ ]:
A = np.array([[[[[1],[2],[3]]],[[[1],[2],[3]]]]])
A.shape

(1, 2, 1, 3, 1)

Zadanie 4

In [ ]:
A = np.random.randint(0,6,(4,5))
A

array([[2, 0, 3, 3, 2],
       [4, 5, 1, 3, 5],
       [5, 2, 3, 2, 1],
       [3, 2, 1, 5, 1]])

In [ ]:
A[1,4]

3

In [ ]:
A[1:3,4]

array([3, 5])

In [ ]:
B = A[1:3,3:5]
B

array([[3, 5],
       [2, 1]])

In [ ]:
B = A[1:3,3:5].copy()
B

array([[2, 1],
       [5, 0]])

In [ ]:
B[0,0]=100

In [ ]:
B

array([[100,   1],
       [  5,   0]])

In [ ]:
A

array([[1, 0, 5, 3, 5],
       [1, 3, 5, 2, 1],
       [3, 5, 2, 5, 0],
       [0, 3, 0, 4, 0]])

In [ ]:
B = A[:,1:3]
B

array([[0, 5],
       [3, 5],
       [5, 2],
       [3, 0]])

In [ ]:
A[1:3,3:5]

array([[3, 3],
       [2, 5]])

In [ ]:
A[1:,3:]

array([[3, 3],
       [2, 5],
       [4, 5]])

Zadanie 4

In [ ]:
A = np.random.randint(0,6,(4,5))
A

array([[1, 0, 5, 3, 5],
       [1, 3, 5, 2, 1],
       [3, 5, 2, 5, 0],
       [0, 3, 0, 4, 0]])

In [ ]:
B = A[:,1:3]
B

array([[0, 5],
       [3, 5],
       [5, 2],
       [3, 0]])

In [ ]:
B1 = A[:,1:3].copy()
B1

array([[0, 5],
       [3, 5],
       [5, 2],
       [3, 0]])

In [ ]:
C = A[1:3,1:5]
C

array([[3, 5, 2, 1],
       [5, 2, 5, 0]])

In [ ]:
C1 = A[1:3,1:5].copy()
C1

array([[3, 5, 2, 1],
       [5, 2, 5, 0]])

Zadanie 5

In [ ]:
D = np.array(np.arange(0,12))
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
D.shape

(12,)

In [ ]:
print(D.reshape(2,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
print(D.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(D.reshape(3,4,1))

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [ ]:
print(D.reshape(3,1,2,1,2))

[[[[[ 0  1]]

   [[ 2  3]]]]



 [[[[ 4  5]]

   [[ 6  7]]]]



 [[[[ 8  9]]

   [[10 11]]]]]


Zadanie 5 (przy 24)

In [ ]:
D = np.array(np.arange(0,24))
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
print(D.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
print(D.reshape(6,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
print(D.reshape(8,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
print(D.reshape(3,8))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
print(D.reshape(2,12))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [ ]:
print(D.reshape(12,2))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [ ]:
print(D.reshape(3,8))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
print(D.reshape(8,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
print(D.reshape(2,2,2,3))

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


In [ ]:
print(D.reshape(2,2,3,2))

[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]


In [ ]:
print(D.reshape(2,3,2,2))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


In [ ]:
print(D.reshape(3,2,2,2))

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


In [ ]:
print(D.reshape(2,4,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
print(D.reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(D.reshape(3,4,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [ ]:
print(D.reshape(3,2,4))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [ ]:
print(D.reshape(4,2,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
print(D.reshape(4,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [ ]:
print(D.reshape(2,6,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [ ]:
print(D.reshape(2,2,6))

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


In [ ]:
print(D.reshape(6,2,2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


Zadanie 6

In [ ]:
c = np.array([[2,4],[1,2]])
d = np.array([[-3,5],[-7,8]])


print("c=\n",c)
print("d=\n",d)
print("c.shape=",c.shape)
print("d.shape=",d.shape)
print(np.concatenate([c,d],axis=0))
print(np.concatenate([c,d],axis=1))
print(np.concatenate([d,c],axis=0))
print(np.concatenate([d,c],axis=1))

c=
 [[2 4]
 [1 2]]
d=
 [[-3  5]
 [-7  8]]
c.shape= (2, 2)
d.shape= (2, 2)
[[ 2  4]
 [ 1  2]
 [-3  5]
 [-7  8]]
[[ 2  4 -3  5]
 [ 1  2 -7  8]]
[[-3  5]
 [-7  8]
 [ 2  4]
 [ 1  2]]
[[-3  5  2  4]
 [-7  8  1  2]]


zadanie 7


In [ ]:
c*d

array([[-6, 20],
       [-7, 16]])

In [ ]:
d+6
d



array([[-3,  5],
       [-7,  8]])

In [ ]:
d*8
d


array([[-3,  5],
       [-7,  8]])

In [ ]:
d-8
d


array([[-3,  5],
       [-7,  8]])

In [ ]:
d/8
d


array([[-3,  5],
       [-7,  8]])

In [ ]:
abs(8)
d


array([[-3,  5],
       [-7,  8]])

In [ ]:
np.exp(d)
d


array([[-3,  5],
       [-7,  8]])

In [ ]:
np.power(d,4)
d

array([[-3,  5],
       [-7,  8]])

In [ ]:
A = np.array([[1],[1]])
A

array([[1],
       [1]])

In [ ]:
A = A+X2
A

array([[1.],
       [1.]])

In [ ]:
A = A-X2
A

array([[1.],
       [1.]])

In [ ]:
A = A*X2
A

array([[0.],
       [0.]])

Zadadnie 8

In [ ]:
c = np.array([[1,1,1],[1,1,1]])
d = np.array([[0,1,2]])

c+d



array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
c= np.array([[0],[1],[2]])
d = np.array([[0,1,2]])
c+d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])