In [53]:
b = 11.0
B = "Ala ma koty"
zm1 = 12
zm2 = 4
Zm3 = "5"

In [11]:
b, B, zm1, zm2, Zm3

(11.0, 'Ala ma koty', 12, 4, '5')

In [10]:
print(b, end='')
print(B)
print(zm1)
print(zm2) 
print(Zm3)

11.0Ala ma koty
12
4
5


In [12]:
type(b), type(B), type(zm1), type(zm2), type(Zm3)

(float, str, int, int, str)

In [13]:
int(b)

11

In [15]:
a,b,c,d=1.0,"tekst",12,100

In [16]:
a,b,c,d

(1.0, 'tekst', 12, 100)

In [24]:
zm1+zm2
print(B+" i psa")
print(b%zm2)
print(b*zm1)
print(b**zm1)
print(B*zm1)


Ala ma koty i psa
3.0
132.0
3138428376721.0
Ala ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma koty


ostanie print(B*Zm3) nie dziala


In [25]:
print(len(B))
print(B[0])
print(B[1])
print(B[3:6])
print(B[3:])
print(B[:6])
print(B[-2])

11
A
l
 ma
 ma koty
Ala ma
t


In [36]:
a= "Początek zdania "
b= " koniec zdania "

In [31]:
a+b

'Początek zdania koniec zdania'

In [37]:
a+str(11)

'Początek zdania 11'

In [38]:
12+13

25

In [39]:
12**3

1728

In [40]:
B = "Ala ma koty"

In [41]:
B[0]

'A'

In [43]:
B[0:2] #interesują nas litery od indeksu 0 do indeksu 2-1

'Al'

In [44]:
B[0:5]

'Ala m'

In [52]:
B[0:],B[:6],B[1:7:2],B[-1],B[6:0:-1]

('Ala ma koty', 'Ala ma', 'l a', 'y', ' am al')

In [55]:
print(B*int(Zm3))

Ala ma kotyAla ma kotyAla ma kotyAla ma kotyAla ma koty
<class 'str'>


(None, None)

In [57]:
print(type(str(3)))

str

In [59]:
type(str(3))

str

In [63]:
Bnew = B[0:7]

In [70]:
Bnew=Bnew+str(3)

In [73]:
Bnew+B[6:]

'Ala ma 3 koty'

In [74]:
B[0:7]+str(3)+B[6:]

'Ala ma 3 koty'

In [77]:
B[7:10]

'kot'

In [76]:
B[7:10]="abc"

TypeError: ignored

nie mozna zrobić podmiany

In [83]:
x=str(input("wprowadz ciąg znaków: "))
print(x)

wprowadz ciąg znaków: testhub
testhub


In [84]:
len(x)

7

In [91]:
x= int(input("Liczba: "))
if x>0:
  print("Liczba>0")
elif x==0:
  print("Liczba = 0")  
else:
  print("Liczba <0")



Liczba: 0
Liczba =0


In [95]:
a=int(input("Wspolczynnik a: "))
b=int(input("Wspolczynnik b: "))
c=int(input("Wspolczynnik c: "))
delta= b*b-4*a*c
print(delta)
if delta>0:
  print("Dwa rozwiazania")
elif delta==0:
  print("Jedno rozwiazanie")  
else:
  print("Brak rozwiazan")

Wspolczynnik a: 1
Wspolczynnik b: 4
Wspolczynnik c: 2
8
Dwa rozwiazania


In [96]:
import math 

In [97]:
math.sqrt(9)

3.0

In [111]:
import math 
a=int(input("Wspolczynnik a: "))
b=int(input("Wspolczynnik b: "))
c=int(input("Wspolczynnik c: "))
if a!=0:
  delta= b*b-4*a*c
  print("Delta")
  print(delta)
  if delta>0:
    print("Dwa rozwiazania")
    print((-b-math.sqrt(delta))/(2*a))
    print((-b+math.sqrt(delta))/(2*a))
  elif delta==0:
    print("Jedno rozwiazanie")  
    print((-b)/(2*a))
  else:
    print("Brak rozwiazan")
else:
  print("Rowanie liniowe jedno rozwiazanie")
  if b!=0: 
    print((-b)/(c1))
  else:
    if c==0:
      print("oo rozwiazan")
    else:
      print("rownanie sorzeczne")
    

Wspolczynnik a: 0
Wspolczynnik b: 5
Wspolczynnik c: 1
Rowanie liniowe jedno rozwiazanie
-5.0


In [112]:
m = [1,2,4,"gfhjg",12.0]

In [114]:
len(m)

5

In [115]:
m[0:4]

[1, 2, 4, 'gfhjg']

In [144]:
m.append(123)
m.append("ooo")
m

[123, 'ooo']

In [118]:
m=[]
m.append(123)
m.append("ooo")
m

[123, 'ooo']

In [119]:
m.append([1,2])
m

[123, 'ooo', [1, 2]]

In [120]:
m+[1,2]

[123, 'ooo', [1, 2], 1, 2]

In [121]:
v= m + [1,2]
v

[123, 'ooo', [1, 2], 1, 2]

In [122]:
v[0]=1000

In [123]:
v

[1000, 'ooo', [1, 2], 1, 2]

In [124]:
lista = [1,2,3]
krotka = (11,22,33)

In [126]:
lista[1]=333
lista

[1, 333, 3]

In [127]:
krotka[1]=444

TypeError: ignored

In [128]:
def fun():
  return 1,"abc",243.0

In [136]:
a,b,c = fun()

In [134]:
print(a)
print(b)
print(c)

1
abc
243.0


In [137]:
a = fun()

In [138]:
a

(1, 'abc', 243.0)

In [139]:
print(a[0])
print(a[1])
print(a[2])

1
abc
243.0


In [140]:
m

[123, 'ooo', [1, 2]]

In [141]:
123 in m

True

In [142]:
12 in m

False

In [143]:
m = []

In [145]:
m.append(12)
m.append(15)
m

[123, 'ooo', 12, 15]

In [146]:
for x in m: 
  print(x)

123
ooo
12
15


In [147]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [149]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9


In [153]:
for i in range(0,13,3): #17
  print(i)

0
3
6
9
12


In [166]:
for i in range(-9,0,2): #18
  print(i)
  if i==-1:
   print(0)


-9
-7
-5
-3
-1
0


In [167]:
lista2=[1,4,-6,10,11,15,20]

In [177]:
suma=0

In [178]:
for i in lista2:
  print(i)
  print(suma)
  suma=suma+int(i)
  


print(suma)

1
0
4
1
-6
5
10
-1
11
9
15
20
20
35
55


In [ ]:
sum(lista2),max(lista2)

In [180]:
a=1
while a<10:
  print(a)
  print("poza pętlą")

Strumieniowane dane wyjściowe obcięte do 5000 ostatnich wierszy.
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1
poza pętlą
1

KeyboardInterrupt: ignored

In [201]:
a=int(input("Wspolczynnik a: "))
b=int(input("Wspolczynnik b: "))
potega=1
i=0
while i<abs(b):
  if b>0:
    potega*=a
    i=i+1
  else:
    potega*=1.0/a
    i=i+1
 

print(potega)-


Wspolczynnik a: 2
Wspolczynnik b: -8
0.00390625


In [199]:
def potega(a,b):
  potega=1
  i=0
  while i<abs(b):
    if b>0:
      potega*=a
      i=i+1
    else:
      potega*=1.0/a
      i=i+1
  return potega


In [200]:
potega(2,-8)

0.00390625

In [203]:
numbers = [55, 4, 92, 1, 104, 64, 73, 99, 20]


In [204]:
def max(a):
  max_value = None
  for num in a:
      if (max_value is None or num > max_value):
          max_value = num
  return(max_value)

In [205]:
max(numbers)

104

In [210]:
def sum(a):
  suma=0
  for i in a:
   
    suma=suma+int(i)
  return(suma)

In [213]:
def info_lista(a):
 return max(a),sum(a)

In [211]:
sum(numbers)

512

In [214]:
info_lista(numbers)

(104, 512)

In [215]:
import numpy as np

In [217]:
a = np.array([1,3,5,2,7])
a

array([1, 3, 5, 2, 7])

In [218]:
b = np.array([1,3,5.0,2,7])
b

array([1., 3., 5., 2., 7.])

In [220]:
b = np.array([3.14, 4, 2, 3],dtype=int)
b

array([3, 4, 2, 3])

In [223]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [229]:
d=np.array([[-3.0,2.3],[0.1,5.0],[8.0,11.0]])
d

array([[-3. ,  2.3],
       [ 0.1,  5. ],
       [ 8. , 11. ]])

In [227]:
e=np.array([[[2,4],[1,2],[8,9]],[[7,6],[-3,4],[0,8]]])
e

array([[[ 2,  4],
        [ 1,  2],
        [ 8,  9]],

       [[ 7,  6],
        [-3,  4],
        [ 0,  8]]])

In [232]:
a.ndim,b.ndim,c.ndim,d.ndim,e.ndim

(1, 1, 3, 2, 3)

In [233]:
a.shape,b.shape,c.shape,d.shape,e.shape

((5,), (4,), (2, 3, 2), (3, 2), (2, 3, 2))